# Generated by Django 2.0.6 on 2018-07-04 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Resume',
        ),
    ]
