# Generated by Django 2.0.6 on 2018-07-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20180704_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='sex',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='askfor',
            new_name='上门时间',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='cometime',
            new_name='孩子基本信息',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='kidinfo',
            new_name='家教要求',
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(blank=True, default=3, max_length=50),
            preserve_default=False,
        ),
    ]
